"""Activité « Plomberie » — le cœur sanitaire du métier.

Chaque pack est autonome : il porte ses produits **et** les prestations qui
vont avec (la pose d'un chauffe-eau est dans le pack Chauffe-eau, à côté du
chauffe-eau). L'artisan ouvre un dossier et coche tout ce dont il a besoin.

Prix : marché français public 2025-2026 HT (Plomberie-Pro, Comptoir des Pros,
Bricoman, GSB) et guides de devis (Travaux.com, Habitatpresto, MesDépanneurs,
AlloTravaux). Ce sont des prix de vente fourniture, pas des prix d'achat pro
(remise courante de 20 à 40 %) — un point de départ à corriger.

TVA : 10 % rénovation logement de plus de 2 ans (art. 279-0 bis), 5,5 % sur
l'équipement énergétique posé par un RGE (art. 278-0 bis A), 20 % sinon.
"""

from decimal import Decimal

from app.catalog.trades.definitions import (
    Activity,
    CatalogPack,
    PackItem,
    prestation as _s,
    produit as _p,
)

_RENO = Decimal("10.00")
_ENERGIE = Decimal("5.50")


PLOMBERIE = Activity(
    slug="plomberie",
    label="Plomberie",
    description="Sanitaires, robinetterie, alimentation, évacuation, eau chaude, dépannage.",
    packs=(
        CatalogPack(
            name="Alimentation et tuyauterie",
            items=(
                _p("Tube cuivre Ø12", "m", "6.20"),
                _p("Tube cuivre Ø14", "m", "6.90"),
                _p("Tube cuivre Ø16", "m", "8.00"),
                _p("Tube cuivre Ø18", "m", "9.50"),
                _p("Tube cuivre Ø22", "m", "12.00"),
                _p("Tube PER Ø12", "m", "0.50"),
                _p("Tube PER Ø16 gainé", "m", "0.62"),
                _p("Tube PER Ø20", "m", "0.95"),
                _p("Tube multicouche Ø16", "m", "1.10"),
                _p("Tube multicouche Ø20", "m", "1.60"),
                _p("Tube multicouche Ø26", "m", "2.40"),
                _p("Gaine ICTA Ø20", "m", "0.30"),
                _p("Nourrice 4 départs", "unité", "55.00"),
                _p("Nourrice 8 départs", "unité", "95.00"),
                _p("Coffret de nourrice", "unité", "70.00"),
                _p("Raccord PER à sertir Ø16", "unité", "3.20"),
                _p("Raccord multicouche à glissement", "unité", "4.50"),
                _p('Raccord laiton 15x21 (1/2")', "unité", "1.90"),
                _p("Coude cuivre à souder Ø14-16", "unité", "0.95"),
                _p("Té cuivre à souder Ø14-16", "unité", "1.10"),
                _p("Vanne d'arrêt à sphère 15x21", "unité", "9.00"),
                _p("Collier de fixation Ø16", "unité", "0.28"),
                _p("Isolant tubulaire polyéthylène", "m", "0.85"),
                PackItem(
                    "Isolant tubulaire caoutchouc",
                    "m",
                    Decimal("3.50"),
                    _RENO,
                    description="Prix à confirmer : aucune source fiable trouvée.",
                ),
                _s("Création d'une alimentation d'eau", "40.00", 45, unit="m"),
                _s("Reprise d'alimentation existante", "120.00", 90),
            ),
        ),
        CatalogPack(
            name="Consommables et fixations",
            items=(
                _p("Ruban téflon", "unité", "1.20"),
                _p("Filasse et pâte à joint", "unité", "8.00"),
                _p("Silicone sanitaire", "unité", "6.00"),
                _p("Mousse expansive", "unité", "8.00"),
                _p("Colle PVC et décapant", "unité", "9.00"),
                _p("Brasure tendre", "unité", "15.00"),
                _p("Sachet de joints fibre et caoutchouc", "unité", "4.00"),
                _p("Rosace de finition", "unité", "2.00"),
                _p("Boîte de chevilles et vis", "unité", "12.00"),
                _p("Collier Atlas", "unité", "1.50"),
                PackItem(
                    "Petites fournitures",
                    "forfait",
                    Decimal("25.00"),
                    _RENO,
                    description="Consommables non détaillés du chantier.",
                ),
            ),
        ),
        CatalogPack(
            name="Dépannage et diagnostic",
            description="Interventions ponctuelles, recherche de panne et débouchage.",
            items=(
                _s("Forfait minimum d'intervention", "110.00", 60,
                   note="Usage courant : 80 à 150 € HT hors fournitures."),
                _s("Débouchage à la ventouse ou au furet manuel", "120.00", 60),
                _s("Débouchage au furet électrique", "220.00", 120),
                _s("Débouchage haute pression", "350.00", 180),
                _s("Inspection vidéo de canalisation", "300.00", 120),
                _s("Recherche de fuite électroacoustique", "180.00", 120),
                _s("Recherche de fuite par thermographie", "250.00", 120),
                _s("Recherche de fuite au gaz traceur", "280.00", 150),
                _s("Recherche de fuite sur canalisation enterrée", "450.00", 240),
                _s("Réparation de fuite sur cuivre ou PER", "130.00", 90),
                _s("Remplacement d'un joint", "70.00", 30),
                _s("Remise en eau et purge du réseau", "90.00", 60),
                _s("Mise hors gel de l'installation", "120.00", 90),
            ),
        ),
        CatalogPack(
            name="Eau chaude sanitaire",
            items=(
                _p("Chauffe-eau électrique 50 L", "unité", "180.00"),
                _p("Chauffe-eau électrique 100 L", "unité", "250.00"),
                _p("Chauffe-eau électrique 150 L", "unité", "300.00"),
                _p("Chauffe-eau électrique 200 L (stéatite)", "unité", "380.00"),
                _p("Chauffe-eau électrique 300 L", "unité", "620.00"),
                PackItem(
                    "Chauffe-eau thermodynamique 200 L",
                    "unité",
                    Decimal("1600.00"),
                    _ENERGIE,
                    description="TVA 5,5 % et aides sous condition de pose par un professionnel RGE.",
                ),
                _p("Chauffe-eau thermodynamique 270 L", "unité", "1950.00", _ENERGIE),
                _p("Chauffe-bain gaz instantané", "unité", "330.00"),
                _p("Ballon ECS à échangeur", "unité", "700.00"),
                _p("Groupe de sécurité", "unité", "14.00"),
                _p("Kit de fixation trépied", "unité", "38.00"),
                _p("Siphon de sécurité", "unité", "5.50"),
                _p("Vase d'expansion sanitaire 8 L", "unité", "38.00"),
                _p("Résistance de chauffe-eau", "unité", "45.00"),
                _p("Anode de protection", "unité", "30.00"),
                _p("Thermostat de chauffe-eau", "unité", "35.00"),
                _s("Pose d'un chauffe-eau électrique", "280.00", 240),
                _s("Pose d'un chauffe-eau thermodynamique", "700.00", 420),
                _s("Détartrage d'un chauffe-eau", "180.00", 120),
            ),
        ),
        CatalogPack(
            name="Évacuation et assainissement",
            items=(
                _p("Tube PVC Ø32", "m", "2.51"),
                _p("Tube PVC Ø40", "m", "2.71"),
                _p("Tube PVC Ø50", "m", "3.00"),
                _p("Tube PVC Ø100", "m", "3.50"),
                _p("Coude PVC Ø40", "unité", "1.20"),
                _p("Coude PVC Ø100", "unité", "3.92"),
                _p("Culotte PVC Ø100", "unité", "13.68"),
                _p("Pipe de WC souple", "unité", "11.92"),
                _p("Siphon de lavabo", "unité", "6.25"),
                _p("Siphon d'évier", "unité", "12.00"),
                _p("Bonde de douche Ø90", "unité", "17.49"),
                _p("Bonde de douche extra-plate", "unité", "33.00"),
                _p("Clapet anti-retour Ø40", "unité", "32.00"),
                _p("Clapet anti-retour Ø100", "unité", "60.00"),
                _p("Aérateur à membrane", "unité", "18.00"),
                _p("Tampon de visite", "unité", "22.00"),
                _p("Pompe de relevage eaux grises", "unité", "150.00"),
                _p("Station de relevage sanitaire", "unité", "400.00"),
                _p("Broyeur sanitaire", "unité", "320.00"),
                _s("Création d'une évacuation", "55.00", 60, unit="m"),
                _s("Pose d'une pompe de relevage", "220.00", 180),
            ),
        ),
        CatalogPack(
            name="Prestations",
            description="Temps passé. Les unités génériques vivent dans le pack Chantier.",
            items=(_s("Main-d'œuvre plomberie", "55.00", 60, unit="heure"),),
        ),
        CatalogPack(
            name="Robinetterie",
            items=(
                _p("Mitigeur de lavabo", "unité", "35.00"),
                _p("Mitigeur d'évier avec douchette", "unité", "80.00"),
                _p("Mitigeur bain-douche", "unité", "62.00"),
                _p("Mitigeur thermostatique de douche", "unité", "110.00"),
                _p("Colonne de douche", "unité", "180.00"),
                _p('Robinet d\'arrêt 1/2"', "unité", "7.00"),
                _p("Robinet équerre", "unité", "6.00"),
                _p("Robinet de machine à laver", "unité", "11.00"),
                _p("Robinet auto-perceur", "unité", "7.00"),
                _p("Flexible inox 50 cm", "unité", "5.00"),
                _p("Douchette et flexible", "unité", "28.00"),
                _p("Barre de douche", "unité", "35.00"),
                _p("Réducteur de pression", "unité", "25.00"),
                _p("Mécanisme de chasse", "unité", "22.00"),
                _p("Robinet flotteur", "unité", "14.00"),
                _s("Remplacement de robinetterie", "180.00", 90),
                _s("Dépose de l'ancienne robinetterie", "60.00", 30),
            ),
        ),
        CatalogPack(
            name="Sanitaires",
            items=(
                _p("WC suspendu avec bâti-support", "unité", "350.00"),
                _p("WC à poser (pack complet)", "unité", "125.00"),
                _p("Abattant de WC", "unité", "29.00"),
                _p("Lavabo céramique", "unité", "125.00"),
                _p("Vasque à poser", "unité", "95.00"),
                _p("Lave-mains", "unité", "55.00"),
                _p("Meuble vasque 60 cm", "unité", "240.00"),
                _p("Meuble vasque 80 cm", "unité", "333.00"),
                _p("Meuble vasque 120 cm double", "unité", "560.00"),
                _p("Receveur de douche 90x90", "unité", "150.00"),
                _p("Receveur de douche 120x90 extra-plat", "unité", "220.00"),
                _p("Paroi de douche fixe", "unité", "250.00"),
                _p("Porte de douche", "unité", "320.00"),
                _p("Baignoire acrylique 170 cm", "unité", "275.00"),
                _p("Tablier de baignoire", "unité", "95.00"),
                _p("Évier inox 1 bac", "unité", "90.00"),
                _p("Évier inox 2 bacs", "unité", "140.00"),
                _p("Barre d'appui PMR", "unité", "45.00"),
                _p("Siège de douche PMR", "unité", "120.00"),
                _s("Pose d'un WC à poser", "180.00", 120),
                _s("Pose d'un WC suspendu (alimentation existante)", "300.00", 240),
                _s("Pose d'un WC suspendu avec création du bâti", "650.00", 480),
                _s("Pose d'un lavabo ou d'une vasque", "180.00", 120),
                _s("Pose d'une douche (receveur et paroi)", "400.00", 300),
                _s("Pose d'une baignoire", "450.00", 300),
                _s("Dépose d'un appareil sanitaire", "70.00", 45),
            ),
        ),
    ),
)
