"""company: activites et qualifications

Revision ID: 3aaad096288d
Revises: 4c6f483c61ce
Create Date: 2026-07-20 15:33:17.081016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3aaad096288d'
down_revision: Union[str, None] = '4c6f483c61ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('activities', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False))
    op.add_column('companies', sa.Column('qualifications', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'qualifications')
    op.drop_column('companies', 'activities')
    # ### end Alembic commands ###
