"""add ai conversation tables

Revision ID: 5be460d241c5
Revises: 6cc7943bff6a
Create Date: 2026-07-18 17:47:40.791257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5be460d241c5'
down_revision: Union[str, None] = '6cc7943bff6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_conversations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=True),
    sa.Column('engine_version', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=False),
    sa.Column('overall_confidence', sa.Float(), nullable=True),
    sa.Column('questions_asked', sa.Integer(), nullable=False),
    sa.Column('draft_line_count', sa.Integer(), nullable=False),
    sa.Column('unresolved_count', sa.Integer(), nullable=False),
    sa.Column('total_duration_ms', sa.Float(), nullable=True),
    sa.Column('timings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('quote_reference', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_ai_conversations_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_conversations'))
    )
    op.create_index(op.f('ix_ai_conversations_company_id'), 'ai_conversations', ['company_id'], unique=False)
    op.create_index('ix_ai_conversations_created_at', 'ai_conversations', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_conversations_engine_version'), 'ai_conversations', ['engine_version'], unique=False)
    op.create_index(op.f('ix_ai_conversations_state'), 'ai_conversations', ['state'], unique=False)
    op.create_table('ai_decisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('source_index', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('catalog_item_id', sa.Uuid(), nullable=True),
    sa.Column('designation', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], name=op.f('fk_ai_decisions_conversation_id_ai_conversations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_decisions'))
    )
    op.create_index(op.f('ix_ai_decisions_catalog_item_id'), 'ai_decisions', ['catalog_item_id'], unique=False)
    op.create_index(op.f('ix_ai_decisions_company_id'), 'ai_decisions', ['company_id'], unique=False)
    op.create_index(op.f('ix_ai_decisions_conversation_id'), 'ai_decisions', ['conversation_id'], unique=False)
    op.create_table('ai_turns',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('stt_confidence', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], name=op.f('fk_ai_turns_conversation_id_ai_conversations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_turns')),
    sa.UniqueConstraint('conversation_id', 'seq', name='uq_ai_turns_conversation_id_seq')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_turns')
    op.drop_index(op.f('ix_ai_decisions_conversation_id'), table_name='ai_decisions')
    op.drop_index(op.f('ix_ai_decisions_company_id'), table_name='ai_decisions')
    op.drop_index(op.f('ix_ai_decisions_catalog_item_id'), table_name='ai_decisions')
    op.drop_table('ai_decisions')
    op.drop_index(op.f('ix_ai_conversations_state'), table_name='ai_conversations')
    op.drop_index(op.f('ix_ai_conversations_engine_version'), table_name='ai_conversations')
    op.drop_index('ix_ai_conversations_created_at', table_name='ai_conversations')
    op.drop_index(op.f('ix_ai_conversations_company_id'), table_name='ai_conversations')
    op.drop_table('ai_conversations')
    # ### end Alembic commands ###
