"""add catalog, clients and quotes tables

Revision ID: 6521371f0e54
Revises: 65a012f34084
Create Date: 2026-07-15 11:10:52.912522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6521371f0e54'
down_revision: Union[str, None] = '65a012f34084'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_categories',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_catalog_categories_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_catalog_categories'))
    )
    op.create_index(op.f('ix_catalog_categories_company_id'), 'catalog_categories', ['company_id'], unique=False)
    op.create_table('clients',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_clients_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clients'))
    )
    op.create_index(op.f('ix_clients_company_id'), 'clients', ['company_id'], unique=False)
    op.create_table('catalog_items',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('designation', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('item_type', sa.Enum('service', 'product', name='catalog_item_type'), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('unit_price_ht', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['catalog_categories.id'], name=op.f('fk_catalog_items_category_id_catalog_categories')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_catalog_items_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_catalog_items'))
    )
    op.create_index(op.f('ix_catalog_items_active'), 'catalog_items', ['active'], unique=False)
    op.create_index(op.f('ix_catalog_items_category_id'), 'catalog_items', ['category_id'], unique=False)
    op.create_index(op.f('ix_catalog_items_company_id'), 'catalog_items', ['company_id'], unique=False)
    op.create_table('quotes',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('total_ht', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_vat', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_ttc', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_quotes_client_id_clients'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_quotes_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quotes'))
    )
    op.create_index(op.f('ix_quotes_client_id'), 'quotes', ['client_id'], unique=False)
    op.create_index(op.f('ix_quotes_company_id'), 'quotes', ['company_id'], unique=False)
    op.create_table('quote_lines',
    sa.Column('quote_id', sa.Uuid(), nullable=False),
    sa.Column('catalog_item_id', sa.Uuid(), nullable=False),
    sa.Column('designation', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_price_ht', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('total_ht', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_vat', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_ttc', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_item_id'], ['catalog_items.id'], name=op.f('fk_quote_lines_catalog_item_id_catalog_items'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], name=op.f('fk_quote_lines_quote_id_quotes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quote_lines'))
    )
    op.create_index(op.f('ix_quote_lines_quote_id'), 'quote_lines', ['quote_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quote_lines_quote_id'), table_name='quote_lines')
    op.drop_table('quote_lines')
    op.drop_index(op.f('ix_quotes_company_id'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_client_id'), table_name='quotes')
    op.drop_table('quotes')
    op.drop_index(op.f('ix_catalog_items_company_id'), table_name='catalog_items')
    op.drop_index(op.f('ix_catalog_items_category_id'), table_name='catalog_items')
    op.drop_index(op.f('ix_catalog_items_active'), table_name='catalog_items')
    op.drop_table('catalog_items')
    op.drop_index(op.f('ix_clients_company_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_catalog_categories_company_id'), table_name='catalog_categories')
    op.drop_table('catalog_categories')
    # ### end Alembic commands ###
    # See bd7d5c7f9cc8's downgrade: DROP TABLE leaves PostgreSQL ENUM types
    # in place, so they have to go explicitly or the next upgrade fails.
    sa.Enum(name='catalog_item_type').drop(op.get_bind(), checkfirst=True)
