"""add company regulatory fields

Revision ID: 76512d9490e4
Revises: 5be460d241c5
Create Date: 2026-07-18 18:24:36.303496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76512d9490e4'
down_revision: Union[str, None] = '5be460d241c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('legal_form', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('share_capital', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('rcs_rm', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('ape_code', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('insurance_name', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('insurance_contract', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('insurance_coverage', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('rge_number', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('payment_terms', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('vat_regime', sa.String(), server_default='normal', nullable=False))
    op.add_column('companies', sa.Column('quote_validity_days', sa.Integer(), server_default='30', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'quote_validity_days')
    op.drop_column('companies', 'vat_regime')
    op.drop_column('companies', 'payment_terms')
    op.drop_column('companies', 'rge_number')
    op.drop_column('companies', 'insurance_coverage')
    op.drop_column('companies', 'insurance_contract')
    op.drop_column('companies', 'insurance_name')
    op.drop_column('companies', 'ape_code')
    op.drop_column('companies', 'rcs_rm')
    op.drop_column('companies', 'share_capital')
    op.drop_column('companies', 'legal_form')
    # ### end Alembic commands ###
