"""add catalog item is_favorite

Revision ID: 7dd52a8e7c70
Revises: 84c5f7af3c3f
Create Date: 2026-07-21 22:21:48.551233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dd52a8e7c70'
down_revision: Union[str, None] = '84c5f7af3c3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # A NOT NULL column added to an already-populated table needs a default to
    # backfill existing rows (all catalog articles start "not in the toolbox").
    # Drop the server default right after so the column matches the model, whose
    # default lives in Python — this also keeps future autogenerate quiet.
    op.add_column(
        'catalog_items',
        sa.Column('is_favorite', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column('catalog_items', 'is_favorite', server_default=None)
    op.create_index(op.f('ix_catalog_items_is_favorite'), 'catalog_items', ['is_favorite'], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_catalog_items_is_favorite'), table_name='catalog_items')
    op.drop_column('catalog_items', 'is_favorite')
    # ### end Alembic commands ###
