"""company: activites et qualifications (jsonb versionne)

Revision ID: 84c5f7af3c3f
Revises: 4c6f483c61ce
Create Date: 2026-07-20 15:50:11.826445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '84c5f7af3c3f'
down_revision: Union[str, None] = '4c6f483c61ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('activities', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('companies', sa.Column('qualifications', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'qualifications')
    op.drop_column('companies', 'activities')
    # ### end Alembic commands ###
