"""add document_analyses table

Revision ID: c68fbf271bcb
Revises: bd7d5c7f9cc8
Create Date: 2026-07-15 07:48:06.800688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c68fbf271bcb'
down_revision: Union[str, None] = 'bd7d5c7f9cc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_analyses',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('document_template_id', sa.Uuid(), nullable=True),
    sa.Column('document_type', sa.Enum('quote', 'invoice', name='document_analysis_type'), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_hash', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('uploaded', 'processing', 'completed', 'failed', name='document_analysis_status'), nullable=False),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('extracted_text', sa.String(), nullable=True),
    sa.Column('extracted_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('detected_layout', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('blueprint', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_document_analyses_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_template_id'], ['document_templates.id'], name=op.f('fk_document_analyses_document_template_id_document_templates'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_analyses'))
    )
    op.create_index(op.f('ix_document_analyses_company_id'), 'document_analyses', ['company_id'], unique=False)
    op.create_index(op.f('ix_document_analyses_file_hash'), 'document_analyses', ['file_hash'], unique=False)
    op.create_index(op.f('ix_document_analyses_status'), 'document_analyses', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_analyses_status'), table_name='document_analyses')
    op.drop_index(op.f('ix_document_analyses_file_hash'), table_name='document_analyses')
    op.drop_index(op.f('ix_document_analyses_company_id'), table_name='document_analyses')
    op.drop_table('document_analyses')
    # ### end Alembic commands ###
    # See bd7d5c7f9cc8's downgrade: DROP TABLE leaves PostgreSQL ENUM types
    # in place, so they have to go explicitly or the next upgrade fails.
    sa.Enum(name='document_analysis_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='document_analysis_type').drop(op.get_bind(), checkfirst=True)
