"""add document_analysis failure_reason

Revision ID: cf9e75cd3b0a
Revises: b2f8a1c9d3e7
Create Date: 2026-07-30 17:25:23.559206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf9e75cd3b0a'
down_revision: Union[str, None] = 'b2f8a1c9d3e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_analyses', sa.Column('failure_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_analyses', 'failure_reason')
    # ### end Alembic commands ###
