"""add company last_active_at (retention)

Revision ID: e0c465a09a0d
Revises: cf9e75cd3b0a
Create Date: 2026-07-30 20:07:55.858701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0c465a09a0d'
down_revision: Union[str, None] = 'cf9e75cd3b0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_companies_last_active_at'), 'companies', ['last_active_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_last_active_at'), table_name='companies')
    op.drop_column('companies', 'last_active_at')
    # ### end Alembic commands ###
